---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.tankes.story
  resources:
  - tankesredismetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.tankes.story
  resources:
  - tankesredismetrics/finalizers
  verbs:
  - update
- apiGroups:
  - core.tankes.story
  resources:
  - tankesredismetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.tankes.story
  resources:
  - tankessqlmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.tankes.story
  resources:
  - tankessqlmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - core.tankes.story
  resources:
  - tankessqlmetrics/status
  verbs:
  - get
  - patch
  - update
