# permissions for end users to edit tankessqlmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tankessqlmetric-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tankes-exporter
    app.kubernetes.io/part-of: tankes-exporter
    app.kubernetes.io/managed-by: kustomize
  name: tankessqlmetric-editor-role
rules:
- apiGroups:
  - core.tankes.story
  resources:
  - tankessqlmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.tankes.story
  resources:
  - tankessqlmetrics/status
  verbs:
  - get
