//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesRedisMetric) DeepCopyInto(out *TankesRedisMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesRedisMetric.
func (in *TankesRedisMetric) DeepCopy() *TankesRedisMetric {
	if in == nil {
		return nil
	}
	out := new(TankesRedisMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TankesRedisMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesRedisMetricList) DeepCopyInto(out *TankesRedisMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TankesRedisMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesRedisMetricList.
func (in *TankesRedisMetricList) DeepCopy() *TankesRedisMetricList {
	if in == nil {
		return nil
	}
	out := new(TankesRedisMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TankesRedisMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesRedisMetricSpec) DeepCopyInto(out *TankesRedisMetricSpec) {
	*out = *in
	if in.LabelMatchingGroups != nil {
		in, out := &in.LabelMatchingGroups, &out.LabelMatchingGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesRedisMetricSpec.
func (in *TankesRedisMetricSpec) DeepCopy() *TankesRedisMetricSpec {
	if in == nil {
		return nil
	}
	out := new(TankesRedisMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesRedisMetricStatus) DeepCopyInto(out *TankesRedisMetricStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesRedisMetricStatus.
func (in *TankesRedisMetricStatus) DeepCopy() *TankesRedisMetricStatus {
	if in == nil {
		return nil
	}
	out := new(TankesRedisMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesSqlMetric) DeepCopyInto(out *TankesSqlMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesSqlMetric.
func (in *TankesSqlMetric) DeepCopy() *TankesSqlMetric {
	if in == nil {
		return nil
	}
	out := new(TankesSqlMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TankesSqlMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesSqlMetricList) DeepCopyInto(out *TankesSqlMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TankesSqlMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesSqlMetricList.
func (in *TankesSqlMetricList) DeepCopy() *TankesSqlMetricList {
	if in == nil {
		return nil
	}
	out := new(TankesSqlMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TankesSqlMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesSqlMetricSpec) DeepCopyInto(out *TankesSqlMetricSpec) {
	*out = *in
	if in.LabelFields != nil {
		in, out := &in.LabelFields, &out.LabelFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesSqlMetricSpec.
func (in *TankesSqlMetricSpec) DeepCopy() *TankesSqlMetricSpec {
	if in == nil {
		return nil
	}
	out := new(TankesSqlMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TankesSqlMetricStatus) DeepCopyInto(out *TankesSqlMetricStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TankesSqlMetricStatus.
func (in *TankesSqlMetricStatus) DeepCopy() *TankesSqlMetricStatus {
	if in == nil {
		return nil
	}
	out := new(TankesSqlMetricStatus)
	in.DeepCopyInto(out)
	return out
}
